### ISSUE TITLE
Problem at first execution

### ISSUE THREAD

**Issue by mh510** [ProbabilisticNumerics/entropy-search#3]
Hello, I recently started working on the topic of entropy search. I would like to test your implementation, but I already got the following error after exetution of "ExampleSetup.m".

```
>> ExampleSetup
executing gpml startup script...
starting entropy search.

iteration number 1
sampling at random

iteration number 2
generating belief and evaluation points.
calling matlab joint_min
evaluating p(x_min)#####Compiling tprod for first use
Building with 'MinGW64 Compiler (C)'.
Undefined function or variable 'out'.
Error in EntropySearch (line 207)
            out.FunEst(numiter,:) = out.FunEst(numiter-1,:);
Error in ExampleSetup (line 38)
result = EntropySearch(in); % the output is a struct which contains GP datasets, which can be evaluated with the gpml toolbox. 
```

I'm using MATLAB 2018b and MINGW64 for mex-compiling. I usually have no problems with my mex-complier. However in this case I could trace back the error to line 144 of file "tprod.m", where an initial mex-compilation process is started. Any ideas how I can fix this error?

The readme says that "The Matlab version of the replaced code resides in the `util` subdirectory", this is not the case, right?

Best regards

Edit: Looks like this is a commen problem with tpod these days (ref. https://de.mathworks.com/matlabcentral/fileexchange/16275-tprod-arbitary-tensor-products-between-n-d-arrays). Any idea for a workaround?

**Comment by philipphennig** [comment]
Hi,

from the error message, it looks like you don’t have the tprod package installed. It’s not delivered with this git repo since it is subject to its own license. You can download it from 

https://www.mathworks.com/matlabcentral/fileexchange/16275-tprod-arbitary-tensor-products-between-n-d-arrays

Hope this helps. Best wishes,

Philipp

**Comment by mh510** [comment]
Hey,

I had some time to get back into this issue. Could you upload your mex-ed tprod files?
